name: Publish Docker image
on:
  push:
    branches: [ master ]
jobs:
  push_to_registries:
    name: Build and push containers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1 
        with:
          registry: julianzp.azurecr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and push hello
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: julianzp.azurecr.io/julianzp/hello:latest
          push: true